# vim: ft=tmux

set -g mode-style "fg=#eee8d5,bg=#073642"

set -g message-style "fg=#eee8d5,bg=#073642"
set -g message-command-style "fg=#eee8d5,bg=#073642"

set -g pane-border-style "fg=#073642"
set -g pane-active-border-style "fg=#eee8d5"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=default"

set -g status-bg default

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#eee8d5,bg=default]#[fg=#073642,bg=#eee8d5,bold] #S:#I.#P  #[fg=#15161E,bg=#93a1a1,bold] #(whoami) #[fg=#93a1a1,bg=default,nobold,nounderscore,noitalics]  "
set -g status-right "#[fg=#93a1a1,bg=default]#[fg=#15161E,bg=#93a1a1,bold] #h #[fg=#93a1a1,bg=default,nobold,nounderscore,noitalics]"

setw -g window-status-activity-style "underscore,fg=#839496,bg=default"
setw -g window-status-separator "  "
setw -g window-status-style "none"
setw -g window-status-current-style "none"
setw -g window-status-format '#[fg=#b58900,bg=default]#[fg=#001419,bg=#b58900] #I #[fg=#073642,bg=#93a1a1] #{b:pane_current_path} #[fg=#93a1a1,bg=default,nobold,nounderscore,noitalics]'
setw -g window-status-current-format '#[fg=#268bd2,bg=default]#[fg=#fdf6e3,bg=#268bd2,bold] #I #[fg=#073642,bg=#fdf6e3,bold] #{b:pane_current_path} #[fg=#fdf6e3,bg=default,nobold,nounderscore,noitalics]'

